config/routes.rb
Rails.application.routes.draw do
  # :as a cusotmized route helper
  root 'home#welcome'
  get  '/about' => 'home#about'

  get    '/home'                 => 'sessions#index'
  get    '/login'                => 'sessions#new'
  get 'google_signup', to: redirect('/auth/google_oauth2'), as: 'google_signup'
  get "/auth/:provider/callback" => "sessions#create"
  post   '/sessions'             => 'sessions#create'
  delete '/logout'               => 'sessions#destroy'

  get    '/companies/:slug'   => 'companies#show', :param => :slug, :as => "company"

  resources :job_applications, :except => [:index, :new, :create] do
    resources :notes, :except => [:index]
  end

  get    '/signup'             => 'users#new'
  post   '/users'              => 'users#create'
  get    '/:slug'              => 'users#show',         :param => :slug, :as => "user"
  get    '/:slug/edit'         => 'users#edit',         :param => :slug, :as => "edit_user"
  patch  '/:slug'              => 'users#update',       :param => :slug
  put    '/:slug'              => 'users#update',       :param => :slug
  delete '/:slug'              => 'users#destroy',      :param => :slug

  get    '/:slug/companies' => 'companies#index', :param => :slug, :as => "companies"

  get    '/:slug/job_applications'      => 'job_applications#index',      :param => :slug, :as => "job_applications"
  get    '/:slug/job_applications/new'  => 'job_applications#new',        :param => :slug, :as => "new_job_application"
  post   '/:slug/job_applications'      => 'job_applications#create'
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
    belongs_to :user
    belongs_to :company
    has_many :notes, :dependent => :destroy
    accepts_nested_attributes_for :company

    validate :start_date_before_end_date

    validates :start_date, :presence => true

    def company_attributes=(company) #setter method
      self.company = Company.find_or_create_by(company)
      self.company.update(company)
    end


    private

    def start_date_before_end_date #self allows you to acess current object
      if self.start_date.present? && self.end_date.present? && ( self.end_date - self.start_date ).to_i < 0
        errors.add(:end_date, "cannot be ahead of start date")
      end
    end
  end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  respond_to :html, :json #formats I want responders to handle


  #/:slug/job_applications
  #job_applications_path
  def index
    redirect_to job_applications_path(current_user) unless user_exists?
    if user_is_current_user?
      @job_application = current_user.job_applications.build.tap{|job_application| job_application.build_company} #allows me to manipulate object
    end
  end

  #/:slug/job_applications
  # job_applications_path
  def create
    redirect_to job_applications_path(current_user) unless user_is_current_user?
    @job_application = @user.job_applications.build(job_application_params) #.build returns a new object of the collection type
    if job_application_dates_valid? && @job_application.save
      respond_with(@job_application, location: job_applications_path) #used location: to overrider redirect_to
    else
      render :index
    end
  end

  # /job_applications/:id
  # job_application_path
  def show
    redirect_to job_applications_path(current_user) unless job_application_exists?
    respond_with(@job_application)
  end

  # /job_applications/:id/edit
  # edit_travel_path
  def edit
    redirect_to job_applications_path(current_user) unless job_application_belongs_to_current_user?
  end


  # /job_applications/:id
  # job_application_path
  def update
    redirect_to job_applications_path(current_user) unless job_application_belongs_to_current_user?
    if job_application_dates_valid? && @job_application.update(job_application_params) then redirect_to job_applications_path(current_user)
    else
      render :edit
    end
  end


  # /job_applications/:id
  # job_application_path
  def destroy
    @job_application.destroy if job_application_belongs_to_current_user?
    redirect_to job_applications_path(current_user)
  end

  private

  def job_application_params
    params.require(:job_application).permit(:position, :location, :status, :start_date, :end_date, :company_attributes => [:name])
  end

  def job_application_exists?
    !!( @job_application = JobApplication.find_by(:id => params[:id]) ) #convert into boolean
  end

  def job_application_belongs_to_current_user?
    @job_application.user_id == current_user.id if job_application_exists?
  end

  def job_application_dates_valid?
    %w[start_date end_date].all? do |attribute| # foo_bar is notation to write an array of strings
      if job_application_params[attribute].blank? # returns true if no elements
        true
      else
        if !!( job_application_params[attribute] =~ /\A\d{4}-\d{1,2}-\d{1,2}\z/ ) # 4 #'s, 1 or 2 #'s, 1 or 2#'s, A and Z whitespace
          yyyymmdd = job_application_params[attribute].split(/\D/).map(&:to_i) #calls a method on array element, proc returns object
          !!Date.new(*yyyymmdd) rescue ( @job_application.errors.add(attribute.to_sym, "is invalid"); false ) # boolean if new date true persist, if not rescue
        else
          @job_application.errors.add(attribute.to_sym, "format is invalid"); false #to_sym returns the symbol
        end
      end
    end
  end
end

app/views/job_applications/_delete_edit.html.erb
<div class="link-secondary-subcontainer">
  <% if user == current_user %>
    <p><%= link_to("Delete", job_application_path(job_application), :method => :delete, :data => {:confirm => "Are you sure?"}) %></p>
    <p><%= link_to("Edit", edit_job_application_path(job_application)) %></p>
  <% end %>
</div>

app/views/job_applications/_job_application_form.html.erb
<%= f.label :start_date, "Application Date", :class => "form-label" %>
<%= f.date_field :start_date, :placeholder => "yyyy-mm-dd", :class => "form-field" %>

<%= f.label :end_date, "Expiration/Due Date (opt)", :class => "form-label" %>
<%= f.date_field :end_date, :placeholder => "yyyy-mm-dd", :class => "form-field" %>

<%= f.fields_for(:company, company) do |c| %>
  <%= c.label :name, "Company Name", :class => "form-label" %>
  <%= c.text_field :name, :class => "form-field" %>
<% end %>

<%= f.label :location, "Job location?", :class => "form-label" %>
<%= f.text_field :location, :class => "form-field" %>

<%= f.label :position, "Position applied for?", :class => "form-label" %>
<%= f.text_field :position, :class => "form-field" %>

<%= f.label :status, "Status of application?", :class => "form-label" %>
<%= f.text_field :status, :class => "form-field" %>

app/views/job_applications/_link_to.html.erb
<a href="<%= job_application_path(job_application) %>" class="link-primary-subcontainer">

  <p>
    <%= job_application.start_date.to_time.strftime("%b %e, %Y") %>
    <% if !!job_application.end_date %>
      &ndash;
      <%= job_application.end_date.to_time.strftime("%b %e, %Y") %>
    <% end %>
    <p>==============================================================</p>
  </p>

  <p><span class="make-bold badge badge-primary text-wrap">Company Name:</span> <span class="make-bold"><%= job_application.company.name %></span></p>

  <p><span class="make-bold badge badge-primary text-wrap">Location:</span> <span class="make-bold"><%= job_application.location.blank? ? "No Location?" : job_application.location %></p>

  <p><span class="make-bold badge badge-primary text-wrap">Job Position:</span> <span class="make-bold"><%= job_application.position.blank? ? "No Position?" : job_application.position %></p>

  <p><span class="make-bold badge badge-primary text-wrap">Application Status:</span> <span class="make-bold"><%= job_application.status.blank? ? "Status Undertermined?" : job_application.status %></span></p>

  <p><span class="make-bold badge badge-primary text-wrap">Notes Created:</span> <span class="make-bold"><%= "#{job_application.notes.size} Application #{"Note".pluralize(job_application.notes.size)}"%></p>

</a>

app/views/job_applications/edit.html.erb
<div class="form-container">

  <div class="form-header-container">
    <h1>Edit Application</h1>
  </div>

  <% if @job_application.errors.any? %>
    <%= render :partial => "shared/form_errors", :locals => {:obj => @job_application} %>
  <% end %>

  <div class="form-body-container">
    <%= form_for @job_application do |f| %>
      <%= render :partial => "job_application_form", :locals => {:f => f, :company => @job_application.company} %>
      <%= f.submit "Update", :class => "form-submit-btn" %>
    <% end %>
  </div>

</div>


<!-- CSS -->
<style type="text/css">
  html, body { height: 5000%;}
  body {
    background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/b1/Grey_background.jpg);
    background-repeat: no-repeat;
    background-position: top center;
    background-size: cover;}
</style>

app/views/job_applications/index.html.erb
<div class="<%= @user == current_user ? "float-content-left-container" : "content-container" %>">

  <div class="content-header-container">

    <% if @user != current_user %>
      <h2 class="header-top">
        <%= @user.username %>
        <div><%= link_to("View by Company", companies_path(@user)) %></div>
      </h2>
    <% end %>

    <button type="button" class="btn btn-success"><h4 id="current_job_applications" class="<%= "left-align" if @user != current_user %>">Current Job Application [<%= @user.current_job_applications.size.to_s %>]</h4></button>

  </div>

  <% @user.current_job_applications.each do |job_application| %>
    <div class="link-body-container">
      <%= render :partial => "delete_edit", :locals => {:job_application => job_application, :user => @user} %>
      <%= render :partial => "link_to", :locals => {:job_application => job_application} %>
    </div>
  <% end %>

  <div class="content-header-container">
  <button type="button" class="btn btn-danger"><h4 id="expired_job_applications" class="<%= "left-align" if @user != current_user %>">Expired Job Applications [<%= @user.expired_job_applications.size.to_s %>]</h4></button>
  </div>

  <% @user.expired_job_applications.each do |job_application| %>
    <div class="link-body-container">
      <%= render :partial => "delete_edit", :locals => {:job_application => job_application, :user => @user} %>
      <%= render :partial => "link_to", :locals => {:job_application => job_application} %>
    </div>
  <% end %>

</div>

<% if @user == current_user %>
  <div class="float-content-right-container">
    <div class="form-container">

      <div class="form-header-container" style="text-align: center">
        <h1>New Application</h1>
      </div>

      <% if @job_application.errors.any? %>
        <%= render :partial => "shared/form_errors", :locals => {:obj => @job_application} %>
      <% end %>

      <div class="form-body-container">
        <%= form_for(@job_application, :url => job_applications_path(current_user), :method => "post") do |f| %>
          <%= render :partial => "job_application_form", :locals => {:f => f, :company => @job_application.company} %>
          <%= f.submit "Create new application", :class => "form-submit-btn" %>
        <% end %>
      </div>

    </div>
  </div>
<% end %>

<!-- CSS -->
<style type="text/css">
  html, body { height: 5000%;}
  body {
    background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/b1/Grey_background.jpg);
    background-repeat: no-repeat;
    background-position: top center;
    background-size: cover;}
</style>

app/views/job_applications/show.html.erb
<div class="content-container">
<br>

<div class="badge badge-dark text-wrap" style="width: 66rem; text-align: center">

    <% if @job_application.user != current_user %>
      <h4 class="header-top"><%= link_to(@job_application.user.username, job_applications_path(@job_application.user)) %></h4>
    <% end %>

    <h1 class="left-align" style="text-align: center">Notes for <%= @job_application.company.name %></h1>


    <h6>
      <%= @job_application.start_date.to_time.strftime("%b %e, %Y") %>
      <% if !!@job_application.end_date %>
        &ndash;
        <%= @job_application.end_date.to_time.strftime("%b %e, %Y") %>
      <% end %>
    <h6>

  </div>
  <br><br>

  <% @job_application.notes.order(:created_at => :desc).each do |note| %>
    <div class="link-body-container">
      <%= render :partial => "notes/delete_edit_note", :locals => {:note => note} if @job_application.user == current_user %>
      <%= render :partial => "notes/link_to_note", :locals => {:note => note} %>
    </div>
  <% end %>

  <% if @job_application.user == current_user %>
    <%= link_to("Create a new note", new_job_application_note_path(@job_application), :class => "form-submit-btn") %>
  <% end %>

</div>

<!-- CSS -->
<style type="text/css">
  html, body { height: 5000%;}
  body {
    background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/b1/Grey_background.jpg);
    background-repeat: no-repeat;
    background-position: top center;
    background-size: cover;}
</style>