config/routes.rb
Rails.application.routes.draw do
  # :as a cusotmized route helper
  root 'home#welcome'
  get  '/about' => 'home#about'

  get    '/home'                 => 'sessions#index'
  get    '/login'                => 'sessions#new'
  get 'google_signup', to: redirect('/auth/google_oauth2'), as: 'google_signup'
  get "/auth/:provider/callback" => "sessions#create"
  post   '/sessions'             => 'sessions#create'
  delete '/logout'               => 'sessions#destroy'

  get    '/companies/:slug'   => 'companies#show', :param => :slug, :as => "company"

  resources :job_applications, :except => [:index, :new, :create] do
    resources :notes, :except => [:index]
  end

  get    '/signup'             => 'users#new'
  post   '/users'              => 'users#create'
  get    '/:slug'              => 'users#show',         :param => :slug, :as => "user"
  get    '/:slug/edit'         => 'users#edit',         :param => :slug, :as => "edit_user"
  patch  '/:slug'              => 'users#update',       :param => :slug
  put    '/:slug'              => 'users#update',       :param => :slug
  delete '/:slug'              => 'users#destroy',      :param => :slug

  get    '/:slug/companies' => 'companies#index', :param => :slug, :as => "companies"

  get    '/:slug/job_applications'      => 'job_applications#index',      :param => :slug, :as => "job_applications"
  get    '/:slug/job_applications/new'  => 'job_applications#new',        :param => :slug, :as => "new_job_application"
  post   '/:slug/job_applications'      => 'job_applications#create'
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :job_applications
    has_many :users, :through => :job_applications
    has_many :notes, :through => :job_applications

    before_validation :create_slug_from_name
    validate :slug_is_present_and_unique

    validates :name, :presence   => true, :uniqueness => true

    def self.search(search)
      if search
        company = Company.find_by(name: search)
        if company
          self.where(company_id: company)
      else
        Company.all
      end
    else
      Company.all
    end
  end


    def self.most_popular(n = 15) #scope method
      self.left_joins(:users).group(:name).order("COUNT(users.id) DESC").limit(n)
    end

    def to_param #allows me override user_id in URL for slug
      self.slug
    end

    private

    def create_slug_from_name #creates slug for company rankings in URL
      self.slug = self.name.try(:parameterize)
    end

    def slug_is_present_and_unique
      if self.slug.present? && self.class.where.not(:id => self.id).where(:slug => self.slug).any?
        errors.add(:name, "(slug) already exists")
      end
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

   #/slug/companies
   # companies_path
   def index
      redirect_to companies_path(current_user) unless user_exists?
      @companies = Company.search(params[:search])
    end


    # /companies/:slug
    # company_path
    def show
      redirect_to companies_path(current_user) unless company_exists?
    end

    private

    def company_params
      params.require(:company).permit(:name, :search)
    end

    def company_exists?
      !!( @company = Company.find_by(:slug => params[:slug]) ) #converts to boolean
    end
  end

app/views/companies/_link_to_job_applications.html.erb
<a href="<%= job_application_path(job_application) %>" class="link-primary-subcontainer">

  <p>
    <%= job_application.start_date.to_time.strftime("%b %e, %Y") %>
    <% if !!job_application.end_date %>
      &ndash;
      <%= job_application.end_date.to_time.strftime("%b %e, %Y") %>
    <% end %>
  </p>

  <p><span class="make-bold badge badge-primary text-wrap">Username:</span> <span class="make-bold"><%= job_application.user.username %></span></p>

<p><span class="make-bold badge badge-primary text-wrap">Position:</span> <span class="make-bold"><%= job_application.position.blank? ? "No Position" : job_application.position %></p>

<p><span class="make-bold badge badge-primary text-wrap">Notes Created:</span> <span class="make-bold"><%= "#{job_application.notes.size} Application #{"Note".pluralize(job_application.notes.size)}"%></p>

</a>

app/views/companies/index.html.erb
<div class="content-container">

<h4>Search by Company:</h4>
  <%= form_tag(companies_path, method: :get) do %>
   <%= text_field_tag(:search, params[:search]) %>
   <%= submit_tag ("Search") %>
   <% end %>


  <% if @user.companies.size < 1 %>

    <div class="content-header-container">
      <h1>Companies (0)</h1>
    </div>
    <%= link_to("Create a new application", job_applications_path(@user), :class => "form-submit-btn") if @user == current_user %>

  <% else %>

    <% @user.uniq_companies.each.with_index(1) do |company, i| %>

      <div class="content-header-container">

        <% if (i == 1) && (@user != current_user) %>
          <h2 class="header-top">
            <%= @user.username %>
            <div><%= link_to("View by Date", job_applications_path(@user)) %></div>
          </h2>
        <% end %>

        <h1 class="text-align: center"><%= company.name %></h1>

      </div>

      <% company.job_applications.where(:user => @user).order(:start_date => :desc).each do |job_application| %>
        <div class="link-body-container">
          <%= render :partial => "job_applications/delete_edit", :locals => {:job_application => job_application, :user => @user} %>
          <%= render :partial => "job_applications/link_to", :locals => {:job_application => job_application} %>
        </div>
      <% end %>

    <% end %>
  <% end %>

</div>

<!-- CSS -->
<style type="text/css">
  html, body { height: 5000%;}
  body {
    background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/b1/Grey_background.jpg);
    background-repeat: no-repeat;
    background-position: top center;
    background-size: cover;}
</style>

app/views/companies/show.html.erb
<div class="content-container">


  <div class="content-header-container">
    <h1 class="text-align: center"><%= @company.name%></h1>
  </div>

  <% @company.job_applications.order(:start_date => :desc).each do |job_application| %>
    <div class="link-body-container">
      <%= render :partial => "job_applications/delete_edit", :locals => {:job_application => job_application, :user => job_application.user} %>
      <%= render :partial => "link_to_job_applications", :locals => {:job_application => job_application} %>
    </div>
  <% end %>

</div>

<!-- CSS -->
<style type="text/css">
  html, body { height: 5000%;}
  body {
    background-image: url(https://upload.wikimedia.org/wikipedia/commons/b/b1/Grey_background.jpg);
    background-repeat: no-repeat;
    background-position: top center;
    background-size: cover;}
</style>