config/routes.rb
Rails.application.routes.draw do
  # :as a cusotmized route helper
  root 'home#welcome'
  get  '/about' => 'home#about'

  get    '/home'                 => 'sessions#index'
  get    '/login'                => 'sessions#new'
  get 'google_signup', to: redirect('/auth/google_oauth2'), as: 'google_signup'
  get "/auth/:provider/callback" => "sessions#create"
  post   '/sessions'             => 'sessions#create'
  delete '/logout'               => 'sessions#destroy'

  get    '/companies/:slug'   => 'companies#show', :param => :slug, :as => "company"

  resources :job_applications, :except => [:index, :new, :create] do
    resources :notes, :except => [:index]
  end

  get    '/signup'             => 'users#new'
  post   '/users'              => 'users#create'
  get    '/:slug'              => 'users#show',         :param => :slug, :as => "user"
  get    '/:slug/edit'         => 'users#edit',         :param => :slug, :as => "edit_user"
  patch  '/:slug'              => 'users#update',       :param => :slug
  put    '/:slug'              => 'users#update',       :param => :slug
  delete '/:slug'              => 'users#destroy',      :param => :slug

  get    '/:slug/companies' => 'companies#index', :param => :slug, :as => "companies"

  get    '/:slug/job_applications'      => 'job_applications#index',      :param => :slug, :as => "job_applications"
  get    '/:slug/job_applications/new'  => 'job_applications#new',        :param => :slug, :as => "new_job_application"
  post   '/:slug/job_applications'      => 'job_applications#create'
end

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-6">
       <!-- Latest compiled and minified CSS -->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>

<% if logged_in? %>

<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand text-white font-weight-bold " href="/welcome">
  <img src="images/AppHub1.jpg" width="35" height="35" class="d-inline-block align-top" alt="" loading="lazy"> AppHub</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white" <%= link_to("Applications", job_applications_path(current_user)) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" <%= link_to("All Companies", companies_path(current_user)) %></a>
      </li>
      <li class="nav-item dropdown text-white">
        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" <%= link_to("Account", user_path(current_user)) %></a>
          <a class="dropdown-item" <%= link_to("Company Rankings", home_path(current_user)) %></a>
          <a class="dropdown-item" <%= link_to("Sign out", logout_path, :method => :delete) %></a>

        </div>
      </li>
    </ul>
  </div>
</nav>

<% else %>

<nav class="navbar navbar-light bg-primary text-white">
  <a class="navbar-brand text-white font-weight-bold" href="/registration">
    <img src="images/AppHub1.jpg" width="35" height="35" class="d-inline-block align-top" alt="" loading="lazy">
     AppHub
  </a>

    <div class="nav-item">
      <div class="header-link"><%= link_to("Log In", login_path) %></div>
      &nbsp;or&nbsp;
      <div class="header-link"><%= link_to("Sign Up", signup_path) %></div>
    </div>


</nav>

<% end %>

<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="utf-6">
       <!-- Latest compiled and minified CSS -->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
    <title>AppHub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= render "layouts/navbar" %>

    <div id="content">
      <div class="container clearfix">
        <%= yield %>
      </div>
    </div>
  
  </body>
</html>